export const IMAGES = {
  drawer_background: require('../assets/images/splash/drawer_background.png'),
  background: require('../assets/images/splash/background.png'),
  background2: require('../assets/images/splash/background2.png'),
  background3: require('../assets/images/splash/background3.png'),
  background4: require('../assets/images/splash/background4.png'),
  background5: require('../assets/images/splash/background5.png'),
  background6: require('../assets/images/splash/background6.png'),
  background7: require('../assets/images/splash/background7.png'),
  background_brand: require('../assets/images/home/nike_background.png'),
  avatar_url: require('../assets/images/user/avatar.jpeg'),
  avatar_url_2: require('../assets/images/user/avatar2.png'),
  not_found: require('../assets/images/notfound/item_not_found.png'),
  favorite_not_found: require('../assets/images/notfound/favorite_not_found.png'),
  splash: require('../assets/images/splash/splash.jpg'),
};

export const ICONS = {
  buy: require('../assets/icons/buy.png'),
  trash: require('../assets/icons/trash.png'),
  cartWhite: require('../assets/icons/cart-white.png'),
  menu: require('../assets/icons/menu.png'),
  home: require('../assets/icons/menu/home2.png'),
  profile: require('../assets/icons/menu/profile2.png'),
  edit_profile: require('../assets/icons/profile/edit_profile.png'),
  location: require('../assets/icons/profile/location.png'),
  setting: require('../assets/icons/menu/setting2.png'),
  logOut: require('../assets/icons/menu/logOut.png'),
  notification: require('../assets/icons/menu/notification2.png'),
  order: require('../assets/icons/menu/order2.png'),
  order_history: require('../assets/icons/profile/order_history.png'),
  search: require('../assets/icons/search5.png'),
  heart: require('../assets/icons/menu/heart2.png'),
  favorite: require('../assets/icons/favorite.png'),
  favorite_outline: require('../assets/icons/favorite_outline.png'),
  nike: require('../assets/icons/brand/nike.png'),
  adidas: require('../assets/icons/brand/adidas.png'),
  van_converse: require('../assets/icons/brand/van_converse.png'),
  show: require('../assets/icons/input/show.png'),
  hide: require('../assets/icons/input/hide.png'),
  email: require('../assets/icons/input/message.png'),
  password: require('../assets/icons/input/password.png'),
  edit_password: require('../assets/icons/profile/edit_password.png'),
  goBack: require('../assets/icons/goBack.png'),
  arrow_right: require('../assets/icons/profile/arrow_right.png')
};
